create table equations
(
    id int4 generated by default as identity,
    created_at timestamp,
    input_one int4 not null,
    input_two int4 not null,
    operation  varchar(255),
    result float8 not null,
    valid      boolean not null,
    primary key (id)
)
